username: shubham-k-jha
profile_url: https://github.com/shubham-k-jha
website: https://shubham-k-jha.github.io/
personal_site_repo: https://github.com/shubham-k-jha/shubham-k-jha.github.io
pong:
  live: https://shubham-k-jha.github.io/pong/
  repository: https://github.com/shubham-k-jha/pong
chess:
  live: https://shubham-k-jha.github.io/Neon-Chess-Chess-vs-AI/
  repository: https://github.com/shubham-k-jha/Neon-Chess-Chess-vs-AI

known_category_map:
  data_analytics:
    - superstore-analysis
    - ecommerce-sales-analysis
    - online-retail-analytics
  data_science:
    - solar-ar-kutsenko-ml
    - online-retail-analytics
  sql_databases:
    - superstore-analysis
    - ecommerce-sales-analysis
    - online-retail-analytics
  bi_visualization:
    - superstore-analysis
  python:
    - solar-ar-kutsenko-ml
    - superstore-analysis
    - ecommerce-sales-analysis
    - online-retail-analytics
  research:
    - solar-ar-kutsenko-ml
